apiVersion: v1
data:
  farm.animalss |
    location=barn
    total=3
    animal.type.first=cow
    animal.type.second=horse
  animal.sounds: |
    verbose=true
    animal.cow.sound=moo
    animal.horse.sound=neigh
kind: ConfigMap
metadata:
  name: animal-config

