kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: sample-network-policy
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/24
    ports:
    - protocol: TCP
      port: 5999

