kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  nameeeeee: pod-creators
subjects:
- kind: User
  name: bob@foo-corp.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pod-creator
  apiGroup: rbac.authorization.k8s.io
